### ISSUE TITLE
Compatibility with Python 3.7

### ISSUE THREAD

**Issue by matthew-brett** [ogrisel/wheelhouse-uploader#27]
Testing with the new Python 3.7, I am getting these errors:

```
$ python -m wheelhouse_uploader upload --local-folder ${TRAVIS_BUILD_DIR}/wheelhouse/ $UPLOAD_ARGS $CONTAINER
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/cython-wheels/venv/lib/python3.7/site-packages/libcloud/utils/files.py", line 86, in read_in_chunks
    raise StopIteration
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/cython-wheels/venv/lib/python3.7/site-packages/wheelhouse_uploader/upload.py", line 45, in upload
    return self._try_upload_once(local_folder, container)
  File "/Users/travis/build/MacPython/cython-wheels/venv/lib/python3.7/site-packages/wheelhouse_uploader/upload.py", line 74, in _try_upload_once
    recently_uploaded=recently_uploaded)
  File "/Users/travis/build/MacPython/cython-wheels/venv/lib/python3.7/site-packages/wheelhouse_uploader/upload.py", line 95, in _update_metadata_file
    for bytes_ in metadata_obj.as_stream():
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/cython-wheels/venv/lib/python3.7/site-packages/libcloud/utils/files.py", line 86, in read_in_chunks
    raise StopIteration
StopIteration
```

https://travis-ci.org/MacPython/cython-wheels/jobs/398198700#L198

Is wheelhouse-uploader compatible with Python 3.7?

**Comment by ogrisel** [comment]
I have tried to bump up the dependency on apache libcloud but then I run into:

https://issues.apache.org/jira/browse/LIBCLOUD-935

I will try to find a work around.

**Comment by ogrisel** [comment]
@matthew-brett I pushed release 0.10.0 that includes support for Python 3.7 (while still supporting python 2.7) and recent versions of apache libcloud.

**Comment by matthew-brett** [comment]
Excellent - thanks a lot for doing that.  Now to try and pull out all those
uses of --no-ssl-check :)

**Comment by ogrisel** [comment]
It's causing another bug:

https://github.com/ogrisel/wheelhouse-uploader/issues/29

Will probably do a stopgap release that pins the libcloud dependency to 2.2.1.

I am also trying to reset my apache password to report the bug upstream.
